--- 
abstract: East Asian Width properties
author: 
  - Audrey Tang <cpan@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.68
license: mit
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Unicode-EastAsianWidth
no_index: 
  directory: 
    - inc
    - t
provides: 
  Unicode::EastAsianWidth: 
    file: lib/Unicode/EastAsianWidth.pm
    version: 1.30
requires: 
  perl: 5.6.0
version: 1.30
